sudo: false
language: python
cache:
  directories:
  - $HOME/.pip-cache/
python:
- '2.7'
- '3.4'
before_install:
- pip install --upgrade pip
install:
- pip install --cache-dir $HOME/.pip-cache -r requirements.txt
- python setup.py develop
script:
- nosetests
notifications:
  email: false
deploy:
  - provider: pypi
    user: philippe.pinard
    password:
      secure: nC/0Lj2H/5BZo4BAhc29fYa6AJZL+UBVfFBcoX57XMA3AD+iCHWH0HJJXoiGvKtP3M/NB1tXAB+5Tj0R6q0bUOiMnf1fulckAVHlPI7r9CfukS62/peWcJYxpsFCOhyiqkTbNnwsX2JdRdrO0U/tUztqWUlazK43ziQCDBdqPp4=
    distributions: sdist bdist_wheel
    on:
      tags: true
      repo: ppinard/matplotlib-scalebar
      all_branches: true
